theme: jekyll-theme-chirpy

lang: en
timezone: America/Los_Angeles

title: Trailing{Closure}
tagline: Explorations on Swift technologies.
description: Projects, explorations, and interesting cases regarding Swift and Apple platforms.
url: "https://trailing-closure.com"

github:
  username: lopsae

social:
  name: Maic Lopez Saenz
  links:
    - https://github.com/lopsae

avatar: /assets/img/avatar.png

toc: true

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

paginate: 10

collections:
  tabs:
    output: true
    sort_by: order

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-include-cache

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/


# Github deploy workflow overrides these values by creating a
# _config-build.yml file.
build_date: Local Build Day, 2026, 10:00 PDT
build_run_id: local_run
build_run_number: 47
build_branch: local_branch
